nelmio_api_doc:
    documentation:
        info:
            title: API Boilerplate
            description: API Boilerplate
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc\.json$) # Accepts routes under /api except /api/doc
