nelmio_api_doc:
    documentation:
        servers:
            -   url: http://localhost/
                description: Localhost
        info:
            title: API Boilerplate
            description: API Boilerplate
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            -   Bearer: [ ]
        paths:
            /api/users/login:
                post:
                    tags:
                        - Users
                    description: Login into the api.
                    responses:
                        '200':
                            description: 'Logged in'
                            content:
                                'application/json':
                                    schema:
                                        properties:
                                            token:
                                                type: string
                                            refresh_token:
                                                type: string
                    requestBody:
                        content:
                            'application/json':
                                schema:
                                    properties:
                                        username:
                                            type: string
                                            example: jdoe@niepodam.pl
                                        password:
                                            type: string
                                            example: secretPasswd
            /api/users/token/refresh:
                get:
                    tags:
                        - Users
                    parameters:
                        -   in: query
                            name: refresh_token
                            schema:
                                type: string
                    responses:
                        '200':
                            description: 'Token refreshed'
                            content:
                                'application/json':
                                    schema:
                                        properties:
                                            token:
                                                type: string
                                            refresh_token:
                                                type: string
    areas: # to filter documented areas
        path_patterns: # an array of regexps (document only routes under /api, except /api/doc)
            - ^/api/users