controllers:
    resource: ../../src/User/API/Controller/
    type: annotation
    defaults:
        _format: json

kernel:
    resource: ../../src/Kernel.php
    type: annotation
    defaults:
        _format: json
